require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - config/**/*
    - db/**/*
    - node_modules/**/*
    - bin/**/*
    - Gemfile
    - spec/rails_helper.rb
    - Rakefile
    - spec/spec_helper.rb
    - app/models/application_record.rb
    - app/helpers/application_helper.rb
    - config.ru

  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*
    - spec/**/*

Style/Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
